const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const code=fs.readFileSync(__dirname+'/static/app.js','utf8');
const helper=code.slice(code.indexOf('function reviewSlice('),code.indexOf('async function loadReview('));
const ctx=vm.createContext({});vm.runInContext(helper,ctx);
const rows=Array.from({length:62},(_,i)=>({respuesta:String(i),batch:i<60?1:2,approved:false}));
const state={status:'pending',batch:'',page:1,size:25};
const allState={status:'pending',batch:'all',page:3,size:25};
const allResult=ctx.reviewSlice(rows,allState);
assert.equal(allResult.batchRows.length,62);assert.equal(allResult.visible.length,12);
assert.equal(allResult.visible.at(-1).batch,2);assert.equal(allState.batch,'all');
let result=ctx.reviewSlice(rows,state);
assert.equal(result.visible.length,25);assert.equal(result.pages,3);
state.page=3;result=ctx.reviewSlice(rows,state);
assert.equal(result.visible.length,10);
rows.slice(0,60).forEach(r=>r.approved=true);
result=ctx.reviewSlice(rows,state);
assert.equal(state.batch,'2');assert.equal(state.page,1);assert.equal(result.visible.length,2);
state.status='approved';result=ctx.reviewSlice(rows,state);
assert.equal(state.batch,'1');assert.equal(result.batchRows.length,60);
state.status='all';state.page=999;result=ctx.reviewSlice(rows,state);
assert.equal(state.page,3);
result=ctx.reviewSlice([],state);assert.equal(result.visible.length,0);assert.equal(state.page,1);
console.log('OK: pagination, pending/approved views, batch advance and empty states');
const pick=code.slice(code.indexOf('function initialReviewQuestion('),code.indexOf('function syncTextSelection('));
vm.runInContext(pick,ctx);
assert.equal(ctx.initialReviewQuestion(['A','B'],{A:{a:{approved:true}},B:{b:{approved:false}}}),'B');
assert.equal(ctx.initialReviewQuestion(['A'],{A:{a:{approved:true}}}),'A');
assert.equal(ctx.initialReviewQuestion([],{}),'');
console.log('OK: initial question prefers pending manual review');
